apiVersion: batch/v1
kind: Job
metadata:
  name: init-bankingappdb-job
spec:
  template:
    spec:
      containers:
        - name: init-bankingappdb-container
          # image: gcr.io/YOUR_PROJECT/init-db:latest
          image: init-bankingappdb:latest  # Use the local image built from Dockerfile
          imagePullPolicy: IfNotPresent
          env:
            - name: PGPASSWORD
              value: "postgres"  # or your actual DB password
      restartPolicy: Never
