apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploy
  labels:
    name: redis-deploy
    app: demo-voting-app

spec:
  replicas: 1
  selector:
    matchLabels:  # must match the pod's labels below
      name: redis-pod
      app: demo-voting-app
      
  template:
    metadata:
      name: redis-pod
      labels:
        name: redis-pod
        app: demo-voting-app  # use for all components to be grouped as a single app
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
