apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deploy
  labels:
    name: result-app-deploy
    app: demo-voting-app
    
spec:
  replicas: 1
  selector: # match and manage pods within the same app
    matchLabels:
      name: result-app-pod
      app: demo-voting-app

  template: #pod creation
    metadata:
      name: result-app-pod
      labels:
        name: result-app-pod
        app: demo-voting-app # use for all the components to be grouped as a single app

    spec:
      containers:
        - name: voting-app
          image: kodekloud/examplevotingapp_result:v1
          ports:
            - containerPort: 80
