apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
    type: front-end

spec:
  containers:
    - name: nginx-container
      image: nginx # use full path for repositories other than Docker Hub
    # - name: myapp
    #   image: my-app
