apiVersion: apps/v1
kind: Deployment
metadata:
  name: pos-app-deployment
  labels:
    name: pos-app-deployment
    app: banking-app
    
spec:
  replicas: 1
  selector: # match and manage pods within the same app
    matchLabels:
      name: pos-app-pod
      app: banking-app

  template: #pod creation
    metadata:
      name: pos-app-pod
      labels:
        name: pos-app-pod
        app: banking-app # use for all the components to be grouped as a single app

    spec:
      containers:
        - name: pos-app-container
          image: pos:2.0.4 # for local testing
          # image: us-central1-docker.pkg.dev/grounded-pivot-466222-u4/my-docker-repo/pos:2.0.4 # to reference the image in Artifact Registry
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"            
