apiVersion: v1
kind: Service
metadata:
  name: banking-app-service  # host name referenced
  labels:
    name: banking-app-service
    app: banking-app  # same to be grouped with the other pod objects
spec:
#  type: NodePort # locally, but for cloud deployments, use LoadBalancer
  type: LoadBalancer
  ports:
    - port: 8082  # service port
      targetPort: 8082  # pod port
      nodePort: 30004  # accessible externally
  selector:  # must match the pod's labels
    name: banking-app-pod
    app: banking-app
